const data = {
  products: [
    {
      _id: 1,
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 120,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 2,
      name: 'Nike Slim shirt',
      slug: 'nike-slim-pants',
      category: 'Shirts',
      image: '/images/d2.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 3,
      name: 'Nike Slim shirt',
      slug: 'nike-large-shirt',
      category: 'Shirts',
      image: '/images/d3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 4,
      name: 'Nike Slim shirt',
      slug: 'nike-large-pants',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 4,
      name: 'Nike Slim shirt',
      slug: 'nike-large-pantsss',
      category: 'Shirts',
      image: '/images/d3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
